### ISSUE TITLE
Bad interaction with factory_girl 4.2.0?

### ISSUE THREAD

**Issue by olivierlacan** [yujinakayama/transpec#113]
On RSpec 2.99.0, I'm seeing every factory in my (green) test suite fail with this message when running transpec 3.1.1:

```
Failure/Error: let(:achievement) { create :achievement, :level }
  FactoryGirl::AttributeDefinitionError:
    Attribute already defined: method
  # ./spec/models/activity_spec.rb:61:in `block (4 levels) in <top (required)>'
  # ./spec/models/activity_spec.rb:60:in `block (4 levels) in <top (required)>'
  # ./spec/models/activity_spec.rb:58:in `block (4 levels) in <top (required)>'
  # ./spec/models/activity_spec.rb:12:in `block (3 levels) in <top (required)>'
  # ./spec/models/activity_spec.rb:10:in `block (3 levels) in <top (required)>'
  # ./spec/models/activity_spec.rb:66:in `block (4 levels) in <top (required)>'
```

Any idea what might be causing this?

**Comment by flyerhzm** [comment]
@olivierlacan what's the original file content? and what command line did you run with transpec?

**Comment by yujinakayama** [comment]
Can you please provide a reproducible example?

**Comment by yujinakayama** [comment]
Closing due to lack of activity.
