### ISSUE TITLE
Undefined constant Transpec

### ISSUE THREAD

**Issue by maca** [yujinakayama/transpec#86]
I have a project I've updated to Rails 4 and Rspec 3.

Specs pass with the should syntax warning. I want to migrate my specs to expect syntax.

Running transpec yields this error:

```
  /tmp/d20140822-30337-1kagkuu/mi-congreso/spec/spec_helper.rb:9:in `<top (required)>': uninitialized constant Transpec (NameError)
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1025:in `require'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1025:in `block in requires='
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1025:in `each'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1025:in `requires='
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration_options.rb:101:in `block in process_options_into'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration_options.rb:100:in `each'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration_options.rb:100:in `process_options_into'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration_options.rb:22:in `configure'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:96:in `setup'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:85:in `run'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:70:in `run'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:38:in `invoke'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/exe/rspec:4:in `<top (required)>'
    from /home/maca/.rbenv/versions/2.1.1/bin/rspec:23:in `load'
    from /home/maca/.rbenv/versions/2.1.1/bin/rspec:23:in `<main>
```

I thought of including transpec in the Gemfile but that yields this other error:

```
  /tmp/d20140822-31497-1l69wyg/mi-congreso/spec/spec_helper.rb:9:in `<top (required)>': undefined method `analyze' for Transpec:Module (NoMethodError)
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1025:in `require'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1025:in `block in requires='
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1025:in `each'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1025:in `requires='
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration_options.rb:101:in `block in process_options_into'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration_options.rb:100:in `each'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration_options.rb:100:in `process_options_into'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/configuration_options.rb:22:in `configure'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:96:in `setup'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:85:in `run'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:70:in `run'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:38:in `invoke'
    from /home/maca/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.4/exe/rspec:4:in `<top (required)>'
    from /home/maca/.rbenv/versions/2.1.1/bin/rspec:23:in `load'
    from /home/maca/.rbenv/versions/2.1.1/bin/rspec:23:in `<main>
```

**Comment by boatrite** [comment]
I have this exact problem.

> The problematic code or the project's URL
I created a dummy project that displays this error.
https://github.com/boatrite/transpec_issue

> Transpec version (transpec --version)
3.2.2

> RSpec version (bundle exec rspec --version)
2.99.2

> Ruby version (ruby --version)
ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux]

> Rails version
4.2.6

> The complete command-line options you passed to transpec
None. Running only `transpec` with no options.

**Comment by boatrite** [comment]
Figured it out. The problem is this line in spec/spec_helper.rb:

`Dir[Rails.root.join("spec/support/**/*.rb")].each {|f| require f}`

Transpec adds `--require ./transpec_analysis_helper.rb` to the `.rspec` file of the copied project, but this doesn't get required until after the files in spec/support are (attempted to be) required.
Since Transpec adds a bunch of analysis code to all the files in spec/support, Transpec is not defined when they are attempted to be required.

The workaround is to manually add `require_relative "../transpec_analysis_helper"` to the spec/spec_helper.rb file before trying to require the support files.

Here's the relevant part of my spec/support file as an example.
```
require 'rubygems'
#uncomment the following line to use spork with the debugger
#require 'spork/ext/ruby-debug'

# Loading more in this block will cause your tests to run faster. However,
# if you change any configuration or code from libraries loaded here, you'll
# need to restart spork for it take effect.

# This file is copied to spec/ when you run 'rails generate rspec:install'
ENV["RAILS_ENV"] ||= 'test'
require File.expand_path("../../config/environment", __FILE__)
require 'rspec/rails'
require 'capybara/rails'
require 'capybara/poltergeist'
require 'rspec/mocks'
require 'factory_girl'

require_relative "../transpec_analysis_helper"

Capybara.register_driver :selenium do |app|
  Capybara::Selenium::Driver.new(app, :browser => :chrome)
end

Capybara.javascript_driver = :poltergeist

# Uncomment this to use the live chrome browser that will pop up.  This is useful for debugging.
# Capybara.javascript_driver = :selenium

# Requires supporting ruby files with custom matchers and macros, etc,
# in spec/support/ and its subdirectories.
Dir[Rails.root.join("spec/support/**/*.rb")].each {|f| require f}
```

Remember to remove the require_relative after running transpec.

**Comment by yujinakayama** [comment]
Thanks for the report. However I couldn't reproduce the issue with https://github.com/boatrite/transpec_issue project.

> Transpec adds `--require ./transpec_analysis_helper.rb` to the `.rspec` file of the copied project, but this doesn't get required until after the files in spec/support are (attempted to be) required.

Hmm, `./transpec_analysis_helper.rb` should be required _before_ the `spec/support` files because:

* RSpec evaluates `.rspec` before running examples
* Transpec add `--require ./transpec_analysis_helper.rb` to _the top_ of `.rspec`

**Comment by mockdeep** [comment]
I was seeing the same problem. It was being thrown because we were shelling out to a rake task inside our `spec_helper.rb`:

```ruby
`rake db:add_functions`
```
